Add skip-to link for improved accessibility
slinkity/slinkity pull request #161
Opened 2022-01-26 18:43 UTC by kylesloper

2022-01-30 22:18 UTC, BenDMyers commented on www/src/_layouts/docs.njk
> +  <main class="docs__container" id="main-content">
Howdy! We should probably add `tabindex="-1"` to this `<main>` to ensure focus moves here in all browsers (including mobile browsers, which tend to struggle with this kind of thing)

More context: <https://benmyers.dev/blog/skip-links/>

2022-01-30 22:20 UTC, BenDMyers requested changes

2022-01-30 22:20 UTC, BenDMyers commented on www/src/_layouts/docs.njk
> +  <main class="docs__container" id="main-content">
More context specifically about needing to set the tabindex: https://axesslab.com/skip-links/

2022-01-30 22:29 UTC, Holben888 reviewed
Thanks for this contribution! I agree with adding a skip-link, but we'll need to address Ben and I's (Ben squared?) comments before merging 👍

2022-01-30 22:29 UTC, Holben888 commented on www/styles/_base.scss
> +@use "tools" as *;
Noticing some link changes in this file. Luckily, we just merged a fix to add stylelint + a pre-commit hook for enforcement. I'd suggest rebasing onto the latest master and giving `npm run lint` a try

2022-01-30 22:31 UTC, BenDMyers requested changes
Hey, @kylesloper! Thank you so much for putting this together. Skip links could be very helpful for folks using these docs, so thank you for this contribution!

One thing I noticed — on the _homepage_, I think it makes a lot of sense to skip to the `<main>` element. However, on the docs pages, I think `<article class="docs__container__content">` would be a better skip target, since that's the unique contents of the page past all of the navlinks, which people would actually want to skip to.

Would you be willing to make the skip target conditional?

2022-01-31 21:31 UTC, kylesloper commented
Sorry for the delayed reply here, I quickly whipped this one up before a surgery I had. In terms of "conditionally" setting the target element, we could do that with some frontmatter magic ✨ but I fear that may be overkill for the docs project.
I have re-defined the aria target for the docs page for now and will commit the new changes.

Let me know if you guys want to go for the conditional setup — it is easily scalable but like I said that might be too much for the docs.

2022-02-01 22:28 UTC, Holben888 commented
@kylesloper Hm, looks like some conflicts came up here. Double check that you've rebased onto the latest `main` to resolve those. Otherwise I think it'll be good to merge 👍

2022-02-01 22:43 UTC, BenDMyers requested changes

2022-02-01 22:43 UTC, BenDMyers commented on www/src/_layouts/docs.njk
> +    <article class="docs__container__content" id="main-content">
Howdy- I left a comment a while back that I think got a little lost, but the skip link target should have a `tabindex="-1"` to ensure that, especially in mobile browsers, focus actually moves here.

2022-02-01 22:43 UTC, BenDMyers commented on www/src/_layouts/home.njk
> +<main class="home__content" id="main-content">
This also should have a `tabindex="-1"` to ensure focus is moved in all devices.

2022-02-04 17:25 UTC, BenDMyers approved these changes

2022-02-04 20:15 UTC, kylesloper commented
Pretty sure I have rebased to slinkity's `main` but still seeing conflicts. @Holben888 Any help here :)

2022-02-08 01:27 UTC, Holben888 approved these changes
Won't be skipping this approval!

2022-02-08 01:27 UTC, merged