fix: accessibility enhancements
slinkity/slinkity pull request #212
Opened 2022-03-26 16:21 UTC by rodneylab

Addresses #173

2022-03-29 08:23 UTC, rodneylab commented on www/src/_layouts/docs.njk
> +                <a href="{{ link.href }}" {% if link.href === page.url %}aria-current="page"{% endif %}>{{ link.title }}</a>
Thanks for reviewing. I'll step out here, happy for you to amend as necessary.

2022-04-05 21:42 UTC, AleksandrHovhannisyan commented on www/src/_layouts/docs.njk
> +                <a href="{{ link.href }}" {% if link.href === page.url %}aria-current="page"{% endif %}>{{ link.title }}</a>
No you're fine! I probably shouldn't be the one reviewing/amending here. I just checked in on the ticket and noticed the PR and figured I'd take a quick peek. I'll let the core maintainers weigh in when they have time.

2022-04-06 22:55 UTC, BenDMyers requested changes
Howdy, @rodneylab! Thank you so much for this contribution.

One thing I've noticed: it seems as though the change in markup structure is causing a change in appearance — specifically, your deploy preview seems to have bullets for each of the list item leaf nodes.

This is the result of the following styles, which you can find in `docs.scss`

```scss
&__side-nav {
  // ...
  > li {
      // ...
      > ul {
        list-style: none;
    }
  }
}
```

This is generating the CSS selector `.docs__side-nav > li > ul` - which won't apply now that we have an extra `nav` layer. It might be worth reworking this selector to not require direct children.

2022-04-18 03:34 UTC, rodneylab commented
> Just a quick question: Do we want to remove `aria-hidden`? This was my ill-informed recommendation in the original ticket, so apologies for the confusion around that.

I'm no accessibility expert, so yourself and others are likely better placed to answer that question.

2022-04-18 15:34 UTC, BenDMyers commented
Sorry for the radio silence! This is a situation that I think could go either way, but my recommendation is to **remove** the `aria-hidden`.

2022-04-19 16:36 UTC, rodneylab commented
> Sorry for the radio silence! This is a situation that I think could go either way, but my recommendation is to **remove** the `aria-hidden`.

not at all! Just made changes, hopefully all good.

2022-04-20 13:45 UTC, merged